name: conda-env

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Miniconda
      uses: goanpeca/setup-miniconda@v1.0.2
    #- name: Install libGL (for OpenCV)
    #  run: |
    #    sudo apt-get update
    #    sudo apt-get install -y libgl1-mesa-glx #libgl1-mesa-dev
    - name : Check conda and python
      run: |
        conda --version
        which python
        conda info --envs
    - name: Create conda environment
      run: | 
        conda env update -f ./environment.yml --prune
        conda install pytest
    - name: Install pylapsy
      run: python ./setup.py install
    - name: Run pytest
      run: pytest
      
