name: conda-env

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install libGL (for OpenCV)
      run: |
        apt-get update
        apt-get install libgtk2.0-dev
    - name: Update conda with environment.yml
      uses: matthewrmshin/conda-action@v1.1
      with:
        args: conda env update -f ./environment.yml
    - name: Install pytest
      uses: matthewrmshin/conda-action@v1.1
      with:
        args: conda install pytest
    - name: Install pylapsy
      uses: matthewrmshin/conda-action@v1.1
      with:
        args: python ./setup.py install
    - name: Run "pytest" with the Conda environment
      uses: matthewrmshin/conda-action@v1.1
      with:
        args: pytest
      
