name: conda-env

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: goanpeca/setup-miniconda@v1.0.2
      with:
        miniconda-version: 'latest'
        activate-environment: tlt

    - name: check installation
      run: |
        conda info
        conda list
        conda info --envs
    #- name: Install libGL (for OpenCV)
    #  run: |
    #    sudo apt-get update
    #    sudo apt-get install -y libgl1-mesa-glx #libgl1-mesa-dev
    - name: Install pytest
      run: | 
        conda install pytest
        conda list pytest
    - name: Install pylapsy
      run: python ./setup.py install
    - name: Run pytest
      run: pytest
      
