name: install-conda

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Update conda with environment.yml
      uses: matthewrmshin/conda-action@v1.1
      with:
        args: conda env update -f ./environment.yml
    - name: Install pytest
      uses: matthewrmshin/conda-action@v1.1
      with:
        args: conda install pytest
    - name: Install pylapsy
      uses: matthewrmshin/conda-action@v1.1
      with:
        args: python ./setup.py install
    - name: Run "pytest" with the Conda environment
      uses: matthewrmshin/conda-action@v1.1
      with:
        args: pytest
      
