name: conda-env

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: s-weigand/setup-conda@v1
    - name: Install libGL (for OpenCV)
      run: |
        sudo apt-get update
        sudo apt-get install -y libgl1-mesa-glx #libgl1-mesa-dev
    - name : Check conda and python
      run: |
        conda --version
        which python
        conda list
    - name: Create conda environment
      run: | 
        conda env create -n tlt -f ./environment.yml
        conda activate tlt
        conda install pytest
    - name: Install pylapsy
      run: python ./setup.py install
    - name: Run pytest
      run: pytest
      
